on:
  push:
    branches:
      - sdx
      - staging
      - prod

name: Lint

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: sdx

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        id: install
        run: |
          npm install

      - name: Lint
        id: lint
        run: |
          npm run lint